### ISSUE TITLE
Convert Library to Typescript

### ISSUE THREAD

**Issue by chase9** [node-alarm-dot-com/node-alarm-dot-com#10]
Typescript allows for safer Javascript and has integration with most IDEs to help the development process. I believe that converting to Typescript will help with the quality of the project as it grows.

**Comment by chase9** [comment]
So far I have the conversion done, along with some of the simpler typings and quality-of-life enhancements to package.json (such as some scripts to run/build). 

I would like some feedback on how the library should be laid out. Right now the source files are in /src and the build artifacts are in /lib. What do you think about this @mkormendy ? I might need to adjust this if it doesn't have drop-in support with the home bridge plugin.

**Comment by mkormendy** [comment]
I personally like the src/ dist/ structure vs the src/ lib/ structure.

**Comment by mkormendy** [comment]
I’ve now started all my new js projects as ts. Happy we’re converting it.

**Comment by chase9** [comment]
Agreed! I've switched to using /dist and I _think_ I've figured out the proper structure and config for NPM packaging. I'm new to this, so I'm going to have to go back through and make sure everything applicable is exported.

**Comment by mkormendy** [comment]
Cool. I await your final pull request out of draft.
