### ISSUE TITLE
Add support for cameras in alarm.com

### ISSUE THREAD

**Issue by simonsickle** [node-alarm-dot-com/node-alarm-dot-com#13]
Alarm.com has some brands who have cameras. The cameras can be seen via "https://www.alarm.com/web/api/video/cameras"

The response looks like this
```json
{
  "data": [
    {
      "id": "XXXXXXXX-XXXX",
      "type": "video/camera",
      "attributes": {
        "supportsSnapShot": true,
        "isRecordingToContinuousCloud": false,
        "canTakeSnapshot": true,
        "canRequestRecording": true,
        "hasSvrSchedule": false,
        "excludedFromVisualVerification": false,
        "liveViewHdToggleEnabled": true,
        "canPanTilt": false,
        "canZoom": false,
        "panTiltPresets": [],
        "preferredPanTiltPreset": null,
        "isNotCommunicating": false,
        "lastSuccessfulSupervision": "2020-10-07T03:12:27.39Z",
        "canStreamToPanel": true,
        "canChangeStreamToPanel": true,
        "canStreamToPanelBeEnabled": true,
        "isStreamToPanelEnabled": false,
        "doorbellChimeType": -1,
        "deviceImagePath": "/web/webimages/camera_images/V723_64px.png?v=2",
        "deviceModel": "ADC-V723",
        "macAddress": "REDACTED",
        "firmwareVersion": "0.5.1.128",
        "publicIp": "REDACTED",
        "privateIp": "REDACTED",
        "port": "40926",
        "httpsPort": "41926",
        "shouldUseEntireImageForSnapshot": false,
        "hasDdnsed": true,
        "usageProtocolMapping": {
          "8": 0,
          "10": 0,
          "6": 1
        },
        "isVirtualCamera": false,
        "supportsLiveView": true,
        "forcedLiveViewAspectRatio": null,
        "canBeSaved": false,
        "canChangeDescription": false,
        "description": "NAME_HERE",
        "deviceModelId": 0,
        "canConfirmStateChange": false,
        "remoteCommandsEnabled": false,
        "hasPermissionToChangeState": false,
        "deviceIcon": {
          "icon": 27
        },
        "batteryLevelNull": null,
        "lowBattery": false,
        "criticalBattery": false
      },
      "relationships": {
        "videoEvents": {
          "data": [],
          "meta": {
            "count": "0"
          }
        },
        "videoSource": {
          "data": {
            "id": "XXXXXXXX-XXXX",
            "type": "video/liveVideoSource"
          }
        },
        "videoSourceHd": {
          "data": {
            "id": "XXXXXXXX-XXXX",
            "type": "video/liveVideoHighestResSource"
          }
        },
        "svrVideoSource": {
          "data": {
            "id": "XXXXXXXX-XXXX",
            "type": "video/videoSources/svrVideoSource"
          }
        },
        "snapshot": {
          "data": {
            "id": "XXXXXXXX-XXXX",
            "type": "video/snapshot"
          }
        },
        "system": {
          "data": {
            "id": "REDACTED",
            "type": "systems/system"
          }
        },
        "stateInfo": {
          "data": null
        }
      }
    }
}
```

And live video
```json
{
  "data": {
    "id": "98885735-2049",
    "type": "video/liveVideoHighestResSource",
    "attributes": {
      "directUrl": "REDACTED",
      "proxyUrl": "REDACTED",
      "errorEnum": 0,
      "streamUsage": "LiveViewWebRtsp",
      "isMjpeg": false,
      "urlEncoded": true,
      "useQuickKeepAlives": false,
      "useNullTerminatingByte": false,
      "proxyStreamTimeoutTime": 180,
      "betaPlayerProxyUrl": "REDACTED",
      "janusGatewayUrl": "wss://adcwebrtcproxy.devicetask.com/janus",
      "janusToken": "REDACTED,alarm.com,janus.plugin.streaming:REDACTED",
      "iceServers": "[{\"urls\":[\"stun:alarmiceserver.devicetask.com:3478?transport=udp\"]},{\"urls\":[\"turn:alarmiceserver.devicetask.com:3478?transport=udp\"],\"username\":\"REDACTED:adc_turnuser\",\"credential\":\"REDACTED=\"}]",
      "spsAndPpsRequired": false,
      "visualVerificationRecord": null,
      "coturnAddressesTuplets": "[{\"public\":\"REDACTED\", \"private\":\"REDACTED\"},{\"public\":\"REDACTED\", \"private\":\"REDACTED\"},{\"public\":\"REDACTED\", \"private\":\"REDACTED\"},{\"public\":\"REDACTED\", \"private\":\"REDACTED\"}]"
    },
    "relationships": {
      "directWebrtcConnectionInfo": {
        "data": null
      }
    }
  },
  "included": [],
  "meta": {
    "transformer_version": "1.1"
  }
}
```

And webrtc is used with janus to connect in the browser.

I think we should be able to setup streams using this information and use the homekit camera functionalities

**Comment by chase9** [comment]
When I originally looked into this they were still using Flash on their website and I was unable to find a good way to get the video information. I just looked again and I see a call to `https://www.alarm.com/web/api/video/liveVideoHighestResSources/<CAMERA-ID>` which returns an object. The direct feed is in that object under data > attributes > betaPlayerProxyUrl.

**Comment by simonsickle** [comment]
I looked at this over the weekend and noticed the URL is encoded base64. After decoding, I got garbage output which signals encryption to me. 

Have you experienced this elsewhere in the api? If so, how have you decrypted the values. 


Another thing I was curious about is if you have ever connected the mobile app to wireshark to determine if that API might be more friendly

**Comment by ifeign** [comment]
Not sure if this is helpful, and I’ve read that in many cases this behavior has been changed, but you used to be able to access alarm.com cameras with RTSP using the username/password: root/adcvideo

**Comment by ifeign** [comment]
Did a little digging and found this about alarm.com encryption https://ahmadnassri.com/blog/alarm-com-camera-vulnerability-exposed/

**Comment by simonsickle** [comment]
I've done a bit more digging and this is what looks like we need to accomplish:

- use API to get Janus (webrtc server) tokens to be used
- issue commands to get stream started to camera
- use gstreamer to take Janus stream and turn it into RTSP

This appears to be somewhat easy as a library for Janus already seems to exist with support for the standard streaming plugin. 

https://github.com/meetecho/janode/blob/master/examples/streaming/src/index.js

The strategy of using gstreamer is already present in the Scrypted software with nest cameras / doorbells, so we may be able to replicate this behavior for HKSV as well as home assistant streaming.

**Comment by bhavsec** [comment]
Any update on this? I am looking to integrate Alarm.com cameras with Homebridge.

**Comment by ifeign** [comment]
> I stopped looking into it and went to a unifi protect based system. The Alarm.com will always have to be restreamed from the cloud and I ultimately wanted something that is local based for better latency and less risk of updates breaking my setup 

I'm about to do the same. I'm keeping the alarm system as it came with my house, but cameras etc are gonna be Unifi

**Comment by chase9** [comment]
Unfortunately I don't have the time or, to be honest, desire to work on a camera functionality for this plugin. It would likely be a different plugin anyways due to the extra work needed for streaming video.

I've personally kept my alarm.com camera but all new cameras have been Wyze. They work fine but if I had to start over I think I would use a different brand (and hard-wire them)! Checkout these projects for a pretty good setup for getting your cameras into homebridge/homeassistant:

https://github.com/mrlt8/docker-wyze-bridge (Makes your cloud Wyze cameras locally available)
https://github.com/gtxaspec/wz_mini_hacks (Semi-custom firmware for Wyze cams to take them off of Wyze's cloud)
https://www.scrypted.app/ (Awesome camera framework which can bridge between homekit and many types of cameras. Has NVR functionality too if you donate)
