### ISSUE TITLE
No way to use this code without MFA?

### ISSUE THREAD

**Issue by Andargor** [node-alarm-dot-com/node-alarm-dot-com#38]
Hello. I wish to use this code to have a simple command-line access to my system (i.e. without something like Homebridge).

I'm getting the following error on authentication that several other people have reported (using the README code for querying status):

`Error: POST https://www.alarm.com/web/Default.aspx failed: No afg cookie: ASP.NET_SessionId=REDACTED; twoFactorAuthenticationId=undefined; cookieTest=1; IsFromNewSite=1; fromASP=; IsFromSeamlessLogin=; login=; ST=`

I've read several issue posts about this here and on the Homebridge plugin page, for which the solution was to "turn on MFA". I do not wish to turn on MFA, and can access alarm.com just fine without it.

I have a Telus account, and have managed to use the solution in this issue on the Homebridge plugin page to setup a specific login for automation: https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/125#issuecomment-1947687211 . However I have setup this automation login without MFA, like my main login, and have limited permissions on it.

During my system install, I received a welcome email with a one-click link to alarm.com that still works flawlessly, no login or MFA required, so I know not using MFA should be possible.

How can I use this code without MFA?

**Comment by Andargor** [comment]
Well, this is embarrassing... I had a typo in my login, when I fixed it, things worked. I will go hide in a corner now.

For future reference, the site does generate a `twoFactorAuthenticationId` cookie on submit, even if MFA is not enabled. It is not static, over several tests I have seen it change. So probably related to application session info.

I will mark completed, thanks, and sorry.

**Comment by chase9** [comment]
No problem, glad you got it figured out!
